spring:
  profiles:
    active: dev

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  rabbitmq:
    host: localhost
    port: 5672
    username: cinebook
    password: Mile123_A
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 3s
          multiplier: 2
          max-interval: 15s

  data:
    redis:
      host: localhost
      port: 6379
      password: Mile123_A

  application:
    name: cinebook-api
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - [%X{traceId}] - %msg%n"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method # Sort API by: GET, POST, PUT, DELETE
    tagsSorter: alpha        # Sort Controller by alphabet

  packages-to-scan: com.cinebook

app:
  payment:
    mock:
      secret: "MOCK_GATEWAY_SECRET_123"
    timeout-minutes: 15

  seat-lock:
    ttl-seconds: 120
    max-hold-minutes: 15
  
  redis:
    verify-token-ttl-minutes: 5

  mail:
    from: ${MAIL_USER}
    verify-base-url: http://localhost:3000/verify-email

  jwt:
    access-secret: ${JWT_ACCESS_SECRET}   # min 32 chars
    access-token-ttl-minutes: 15          # 15 minutes
    refresh-token-ttl-days: 7             # 7 days

rabbitmq:
  exchange: cinebook.exchange
  mail:
    queue: cinebook.auth.mail.queue
    routing-key: auth.user.registered
  review:
    queue: cinebook.review.queue
    routing-key: review.interacted

  dlx: cinebook.dlx
  dlq:
    mail:
      queue: cinebook.auth.mail.dlq
      routing-key: auth.mail.dlq.key
    review:
      queue: cinebook.review.dlq
      routing-key: review.dlq.key

minio:
  endpoint: http://localhost:9000
  bucket: cinebook
  access-key: cinebook
  secret-key: cinebook123
  public-base-url: http://localhost:9000/cinebook